services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - internal
      - monitoring

networks:
  internal:
    external: true
  monitoring:
    external: true