services:
  tandoor:
    image: vabene1111/recipes:latest
    container_name: tandoor
    restart: unless-stopped
    depends_on:
      - tandoor-db
    ports:
      - "9926:8080"   # opcjonalnie; usuń, jeśli dostęp tylko przez Nginx Proxy Manager
    env_file:
      - .env
    volumes:
      - ../../data/tandoor/media:/opt/recipes/mediafiles
      - ../../data/tandoor/static:/opt/recipes/staticfiles
    networks:
      - proxy

  tandoor-db:
    image: postgres:16-alpine
    container_name: tandoor-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../../data/tandoor/postgres:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true